// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmQtnbbaLuob-DceTWUj4e5sEqB8ryl_0',
    appId: '1:558661092763:web:5c874053fd8429dd3d4d3e',
    messagingSenderId: '558661092763',
    projectId: 'agrolink-a20a5',
    authDomain: 'agrolink-a20a5.firebaseapp.com',
    storageBucket: 'agrolink-a20a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChzCFoowgl2b94NL-CmhyPg6ESXKUvWZk',
    appId: '1:558661092763:android:5533ef5294373a8a3d4d3e',
    messagingSenderId: '558661092763',
    projectId: 'agrolink-a20a5',
    storageBucket: 'agrolink-a20a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX1c2uHlW-tpkyeRstJLf59ltp2D2l5Fw',
    appId: '1:558661092763:ios:8de1ad544548c8c63d4d3e',
    messagingSenderId: '558661092763',
    projectId: 'agrolink-a20a5',
    storageBucket: 'agrolink-a20a5.firebasestorage.app',
    iosBundleId: 'com.example.agrolink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX1c2uHlW-tpkyeRstJLf59ltp2D2l5Fw',
    appId: '1:558661092763:ios:8de1ad544548c8c63d4d3e',
    messagingSenderId: '558661092763',
    projectId: 'agrolink-a20a5',
    storageBucket: 'agrolink-a20a5.firebasestorage.app',
    iosBundleId: 'com.example.agrolink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmQtnbbaLuob-DceTWUj4e5sEqB8ryl_0',
    appId: '1:558661092763:web:538badcaeb74237b3d4d3e',
    messagingSenderId: '558661092763',
    projectId: 'agrolink-a20a5',
    authDomain: 'agrolink-a20a5.firebaseapp.com',
    storageBucket: 'agrolink-a20a5.firebasestorage.app',
  );
}
